.PHONY: all clean neural_network solver gui

all: neural_network solver gui

clean: neural_network_clean solver_clean gui_clean

neural_network:
	    $(MAKE) -C "Neural Network/"

solver:
	    $(MAKE) -C Solver

gui:
	    $(MAKE) -C Gui

neural_network_clean:
	    $(MAKE) -C "Neural Network/" clean

solver_clean:
	    $(MAKE) -C Solver clean

gui_clean:
	    $(MAKE) -C Gui clean

